services:
    db:
        image: mysql:9.0.1
        ports: 
            - "3306:3306"
        #command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
        env_file:
            - .env
    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html
        links:
            - db
        networks:
            - default
        extra_hosts:
            - "host.docker.internal:host-gateway"
        # Variables de entorno para phpmyadmin y entorno web
        environment:
            MYSQL_USER: ${MYSQL_USER_WEB}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD_WEB}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_WEB}
        env_file:
            - .env
    phpmyadmin:
        image: phpmyadmin:5.2.1
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: ${MYSQL_USER_WEB}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD_WEB}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_WEB}
        env_file:
            - .env
volumes:
    persistent:
